config/routes.rb
Rails.application.routes.draw do

  root             'main#home'
  get 'main/home' => 'main#home'
  get 'signup' => 'users#new'
  get 'users/show' => 'users#show'
  get 'users/edit' => 'users#edit'
  get 'users/termin' => 'users#termin'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  post 'tracks/show' => 'tracks#show'
  get 'tracks/search' => 'tracks#search'
  get 'tracks/edit' => 'tracks#edit'
  get 'tracks/index' => 'tracks#index'
  get 'tracks/input' => 'tracks#input'
  get 'tracks/delete' => 'tracks#delete'
  get 'tracks/details' => 'tracks#details'
  get 'tracks/new' => 'tracks#new'
  post 'tracks/details' => 'tracks#details'
  post 'listazeljas/index' => 'listazeljas#index'
  get 'listazeljas/index' => 'listazeljas#index'
  get 'listazeljas/add' => 'listazeljas#add'
  get 'listazeljas/delete' => 'listazeljas#delete'
  post 'listazeljas/delete' => 'listazeljas#delete'
  get 'listazeljas/potvrdi' => 'listazeljas#potvrdi'
  post 'listazeljas/potvrdi' => 'listazeljas#potvrdi'
  get 'playlists/index' => 'playlists#index'
  get 'playlists/potvrdi' => 'playlists#potvrdi'
  get 'playlists/add' => 'playlists#add'
  get 'playlists/delete' => 'playlists#delete'
  get 'playlists/get_zelje' => 'playlists#get_zelje'
  get 'uredi_urednikes/index' => 'uredi_urednikes#index'
  get 'uredi_urednikes/add' => 'uredi_urednikes#add'
  get 'uredi_urednikes/delete' => 'uredi_urednikes#delete'
  get 'uredi_urednikes/search' => 'uredi_urednikes#search'
  post 'uredi_urednikes/show' => 'uredi_urednikes#show'
  get 'playlists/show' => 'playlists#show'
  get 'playlists/new' => 'playlists#new'
  post 'playlists/new' => 'playlists#new'
  get 'administrators/index' => 'administrators#index'
  get 'administrators/add' => 'administrators#add'
  get 'administrators/delete' => 'administrators#delete'
  get 'administrators/search' => 'administrators#search'
  get 'administrators/show' => 'administrators#show'
  post 'administrators/show' => 'administrators#show'
  get 'administrators/online' => 'administrators#online'
  post 'playlists/create' => 'playlists#create'
  get 'reports/show' => 'reports#show'
  get 'reports/reproduced' => 'reports#reproduced'
  get 'reports/prefered' => 'reports#prefered'
  get 'reports/freq' => 'reports#freq'
  post 'reports/freq_show' => 'reports#freq_show'
  get 'vlasniks/index' => 'vlasniks#index'
  get 'vlasniks/add' => 'vlasniks#add'
  get 'vlasniks/delete' => 'vlasniks#delete'
  get 'vlasniks/info' => 'vlasniks#info'
  post 'vlasniks/edit' => 'vlasniks#edit'
  get 'reports/prefered_show' => 'reports#prefered_show'
  
  resources :users
  resources :account_activations,only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :tracks

end

app/views/auxiliary/_login_modal.html.erb
<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="loginmodal-container">
      <h1>Prijava</h1><br>

      <%= form_for(:session, url: login_path,remote: true) do |f| %>
          <div class="input-group">
            <span class="glyphicon glyphicon-user input-group-addon"></span>
            <%= f.text_field :name,:placeholder=> "Korisnicko ime" , class: 'form-control' %>
          </div>
          </br>
          <div class="input-group">
            <span class="glyphicon glyphicon-lock input-group-addon"></span>
            <%= f.password_field :password, :placeholder=> "Sifra", class: 'form-control' %>
          </div>
          </br>

          <div class="remember-me">
            <%= f.label :remember_me, class: "checkbox inline" do %>
                <%= f.check_box :remember_me %>
                <span>Zapamti me</span>
            <% end %>
          </div>

          <%= f.submit "Prijavi se", class: "login loginmodal-submit" %>
      <% end %>

      <div class="login-help">
        <%= link_to 'Zaboravili ste lozinku', new_password_reset_path %>
      </div>
    </div>
  </div>
</div>